### ISSUE TITLE
How to delete gene names when using circos_heatmap funnction?

### ISSUE THREAD

**Issue by yunbokai** [cran/TOmicsVis#1]
Hi, Thanks for your greate package!
    I wang to use circos_heatmap fuction. However, my data have too much genes and I don't want to show them or I just want show some of them. What should I do?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by yunbokai** [comment]
Thanks
